In [3]:
list_1 = [123, 213214, 546, 24, -123]

In [4]:
list_1

[123, 213214, 546, 24, -123]

In [5]:
import numpy as np

In [6]:
np.array(list_1)  #convert list into array

array([   123, 213214,    546,     24,   -123])

array:
- One data type only

list:
- could contain different data type, such as int, bool, string etc.


In [7]:
b = np.array([12,455, 63.3, True, "abc"])

In [8]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [9]:
print(b) # convert to string during the convertion from list to array

['12' '455' '63.3' 'True' 'abc']


In [10]:
list_1.pop()

-123

In [11]:
list_1

[123, 213214, 546, 24]

In [12]:
a = np.array(list_1)

In [13]:
a

array([   123, 213214,    546,     24])

In [14]:
a.mean()

53476.75

In [15]:
list_1[1:]

[213214, 546, 24]

---

#### listname[start:end:steps]

In [16]:
b = a[2:4]

In [17]:
b

array([546,  24])

In [18]:
b[:] = 111

In [19]:
b[0]

111

In [20]:
b

array([111, 111])

In [21]:
a

array([   123, 213214,    111,    111])

- When actually changing the value in list b, it will change the orginal value in list a
- If you wanna change the value in a copy list, you should use list.copy()

## Critical Difference Between Slicing lists & arrays
1. Slicing a list: **create a copy**of that list
2. Slicing an array: **create a view value**of that array(not a copy)

In [22]:
c = a.copy()

In [23]:
c

array([   123, 213214,    111,    111])

In [24]:
c[0] = 0

In [25]:
c

array([     0, 213214,    111,    111])

In [26]:
a

array([   123, 213214,    111,    111])